name: pip-test

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  workflow_dispatch:

env:
  GITHUB_ACTIONS: true

jobs:
  build-wheel:
    strategy:
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.8.3"]

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Build package
        run: |
          make build

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl

  pip-test:
    needs: [build-wheel]
    strategy:
      matrix:
        os-version: ["ubuntu-latest"]
        python-version: ["3.11"]

    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install numpy==1.26.4
          pip install opencv-python==4.10.0.84

          cd dist
          pip install *.whl

      - name: Install PyTorch on Windows
        if: matrix.os-version == 'windows-latest'
        run: |
          torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1 --index-url https://download.pytorch.org/whl/cu128

      - name: Install PyTorch on non-Windows
        if: matrix.os-version != 'windows-latest'
        run: |
          torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1

      - name: Test pip
        run: |
          cd scripts
          python gen_config.py
          python CItestpip.py
